### ISSUE TITLE
How to understand symmetries in the pbc example 

### ISSUE THREAD

**Issue by Geositta2000** [yangcal/symtensor#4]
I am trying  to understand  the example
https://github.com/yangcal/symtensor/blob/master/symtensor/test/test_pbc.py
  ```
sym_phys = ['++--', [kpts,]*4, None, gvec]
sym_chem = ['+-+-', [kpts,]*4, None, gvec]
sym_t1 = ['+-',[kpts,]*2, None, gvec]
```
  May I know what do these symmetry notations mean? Chemist notation for 2-e integral has symmetries (ab|cd) = (ba|cd) = (ab|dc) = (ba|dc) = (cd|ab) = ...
  how do they related to `++--`? What does `+-` in `sym_t1` mean?

**Comment by yangcal** [comment]
Hello, 
under physics notation, the full indices for the integral should be listed out as `<ki,i,kj,j|ka,a,kb,b>` where ki,kj,ka,kb denote the kpoints of the orbital. In order for this integral to be non-vanishing, the kpoints must satisfy `ki+kj - ka - kb =  nG` where `G` is the reciprocal lattice vector.  You can see here the `+ki+kj-ka-kb` translates to the `'++--'` string and each kpoints enumerates over  kpts. That's where the `sym_phys = ['++--', [kpts,]*4, None, gvec]` is from.

Note here that when orbitals are complex, the symmetry for chemists integrals does not always apply. For instance, `(ka,a,kb,b|kc,c,kd,d) = (kc,c,kd,d|ka,a,kb,b)` but `(ka,a,kb,b|kc,c,kd,d) != (kb,b,ka,a|kc,c,kd,d)` (due to integral being complex). For introduction on the integrals in pbc, you can refer to Equation 23 in this [paper](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.7b00049) and derive all the possible equivalent variants.

For t1, the excitation operator must conserve crystal momentum, therefore for t1[ki,i,ka,a], we must have `ki-ka=nG` and that translates to the string `'+-'`

Let me know if you have other questions.

**Comment by Geositta2000** [comment]
Thanks for your answer. So is the `symtensor` more about periodic condition than the 8-fold symmetries of two-electron integrals?

In https://github.com/yangcal/symtensor/blob/master/symtensor/test/test_multi_operands.py
`    def test_dmrg(self):` 
`        sym1 = ['++-', [ni,nj,nk], None, None]`
`        sym3 = ['++--', [nn,no,nj,nl], None, None]`
`        ijk = st.random([nbond,]*3, sym1)`
`        nojl = st.random([nbond,]*4, sym3)`

are they all about periodic conditions, than one may expect symmetry within indices like `t_{ijk} = t_{jik}`,  `t_{nojl} =  ±t_{onjl}`?

**Comment by yangcal** [comment]
The DMRG test you're looking at is focusing on particle number conservation (U1 symmetry) in MPS-MPO tensors and `symtensor` does not support permutational symmetry (the 8-fold symmetries of two-electron integrals).

**Comment by Geositta2000** [comment]
thanks
